version: '3'

services:
  master:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile-php
      args:
        - DEPLOY_ENV=${APP_ENV}
    image: master-image
    volumes:
      - ./storage:/app/storage
    networks:
      - redis-network
    depends_on:
      - redis
    command: /bin/bash /docker-entrypoint.sh
    tty: true

  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile-nginx
      args:
        - DEPLOY_ENV=${APP_ENV}
    ports:
      - ${APP_PORT}:80
    networks:
      - fastcgi-network
    depends_on:
      - web
    command: nginx -g "daemon off;"
    tty: true

  web:
    restart: unless-stopped
    image: master-image
    volumes:
      - ./storage:/app/storage
    networks:
      - redis-network
      - fastcgi-network
    depends_on:
      - master
    expose:
      - 9000
    command: php-fpm --fpm-config /php-fpm.conf
    tty: true
    stop_signal: SIGKILL

  worker:
    restart: unless-stopped
    image: master-image
    volumes:
      - ./storage:/app/storage
    networks:
      - redis-network
    depends_on:
      - master
    command: php /app/artisan queue:work
    tty: true
    stop_signal: SIGTERM

  redis:
    restart: unless-stopped
    image: redis:alpine
    volumes:
      - redis-db:/data
    networks:
      - redis-network
    command: redis-server --appendonly yes
    tty: true

volumes:
  redis-db:
    driver: local

networks:
  redis-network:
    driver: bridge

  fastcgi-network:
    driver: bridge
