# Compile all the assets!
FROM node:lts-alpine AS assets

ARG BUILD_ENV

COPY . /app
WORKDIR /app

RUN npm install \
    && if [[ "BUILD_ENV" = "production" ]]; \
        then npm run production; \
        else npm run development; \
    fi

# Generate Diffie-Hellman keys!
FROM frapsoft/openssl AS dhparam
RUN openssl dhparam -out /dhparam.pem 2048

# The main HTTP server!
FROM nginx:mainline-alpine

RUN mkdir /app

COPY --from=assets /app/public /app/public
COPY .docker/nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=dhparam /dhparam.pem /etc/nginx/dhparam.pem

EXPOSE 80

ENTRYPOINT []
