# Compile all the assets!
FROM node:lts-alpine AS assets

ARG DEPLOY_ENV

COPY . /app
WORKDIR /app

RUN npm install \
    && if [[ "$DEPLOY_ENV" = "production" ]]; \
        then npm run production; \
        else npm run development; \
    fi

# Generate Diffie-Hellman keys!
FROM frapsoft/openssl AS dhparam
RUN openssl dhparam -out /dhparam.pem 2048

# The main HTTP server!
FROM nginx:1.19.2-alpine

EXPOSE 80

VOLUME /app/public/mix-manifest.json
VOLUME /app/php-fpm.sock
VOLUME /app/logs

RUN mkdir /app

COPY --from=assets /app/public /app/public
COPY .docker/nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=dhparam /dhparam.pem /app/nginx
